### get all users

GET http://localhost:8000/users

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "_id": "6393d7656cdb41833dac435c",
    "lName": "Aryqweal",
}

###  update 
PUT  http://localhost:8000/users
Content-Type: application/json

{
    "_id": "6393d7656cdb41833dac435c",
    "password" : "asdfg"
}

### Delete
DELETE  http://localhost:8000/users/6393d74f6cdb41833dac4357
